modLoader="javafml"
loaderVersion="[43,)"
license="MPL-2.0"
[[mods]]
modId="mermod"
version="1.11"
displayName="Mermod"
logoFile="icon.png"
credits="albertosaurio65, Junnaturefox"
authors="ThatPreston"
description='''
Mermod adds a magical necklace that transforms you into a merperson in water!
'''
[[dependencies.mermod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
