modLoader="javafml"
loaderVersion="[45,)"
license="MPL-2.0"
[[mods]]
modId="mermod"
version="1.3"
displayName="Mermod"
logoFile="icon.png"
credits="albertosaurio65, Junnaturefox"
authors="ThatPreston"
description='''
Mermod adds a magical necklace that transforms you into a merperson in water!
'''
[[dependencies.mermod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"